### ISSUE TITLE
DP: Solve the same problem as above when the fisherman can begin and end at any point. Fish values may be negative.

### ISSUE THREAD

**Issue by Chinmay26** [Apollys/EPI-Variants-Solutions#2]
The best way is to fill the DP array

1. Bottom-up from last row to first
2. Right to left

DP[i][j] = fish[i][j] + max(DP[i+1][j], DP[i][j+1])

Max(DP) will give the best starting point

**Comment by Apollys** [comment]
This way works as well, but the problem is completely symmetrical.  Note there's no difference between walking up-left and walking down-right (either way your scores is simply the sum of all the squares along the path), so your solution is actually exactly the same as mine!

Edit: Oh and remember to handle the negative case! You need to "restart" your path if the cumulative score goes negative.

**Comment by Chinmay26** [comment]
Yes. You are right!
My proposed solution is incorrect. I had based this solution on incorrect assumption that the end point is always bottom right cell.
