### ISSUE TITLE
Compute a shortest addition chain exponentiation sequence to evaluate x^n.

### ISSUE THREAD

**Issue by Chinmay26** [Apollys/EPI-Variants-Solutions#7]
I suspect we can use BFS to solve this. However, dynamic programming seems a better fit for this.

Let distance[n] = shortest path to compute x ^ n

We have distance[n] = min ( distance[i] + distance[n-i]) + 1 for all i<n. Both product of terms and square of term included in this.
Initialize distance[0] = distance[1] = 1; distance[2]=2

So this can be solved in O(N*N) time and O(N) space. We can also use BFS to solve this but I believe DP is a natural fit.

**Comment by Apollys** [comment]
Yes, this is definitely doable in O(n<sup>2</sup>) time with a DP algorithm.

However, I was hoping maybe I could think of something better.  If we think of the input value as n, then the *size* of the input is actually log(n), and that makes this solution seem very inefficient at O(2<sup>2*log(n)</sup>).

I should definitely write up some solution though, rather than just leaving it blank.  I will do that if I don't think of something better soon.  Thanks for reminding me of this one!

**Comment by Chinmay26** [comment]
I believe it still reduces down to N*N. 

O(2 <sup>2*log(n)</sup> ) == O (2 <sup> log (n <sup>2 </sup>) </sup>) == O(n <sup> 2 </sup>)

**Comment by Apollys** [comment]
Wrote this one up.  Maybe if you check it out you'll understand what I mean about exponential time.

Yes, your math is 100% correct.  But what does complexity analysis measure in general?  If I give you an array of `n` elements and ask you to sort them, you'll tell me the time complexity in terms of `n`.  But what is `n`?

`n` is not the value of the input data, it's the *size* of the input data.

And so if my input data is only one number, an integer n, then the *size* of the input data is log<sub>2</sub>(n).

Thus, an O(n) algorithm in that case becomes exponential in the input size.
